name: Part 1 Documentation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-part1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check docs folder exists
        run: test -d docs

      - name: Check ERD PDF exists
        run: test -f docs/RaceDay_ERD.pdf

      - name: Check API Endpoint Plan PDF exists
        run: test -f docs/RaceDay_API_EndPoint_Plan.pdf

      - name: Check SQL Script exists
        run: test -f docs/RaceDay_Database.sql

      - name: Check README.md exists
        run: test -f README.md
